version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: contest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 05052001
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d  # Directory init script
    networks:
      - online-contest-net
    restart: unless-stopped

  mongodb:
    image: mongodb/mongodb-community-server:7.0-ubi9
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root  # username root
      MONGO_INITDB_ROOT_PASSWORD: example  # password root
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db  # Volume for MongoDB data
      - ./mongo-init:/docker-entrypoint-initdb.d  # Directory init script
    networks:
      - online-contest-net
    restart: unless-stopped

volumes:
  postgres-data:  # Volume for PostgreSQL
    driver: local
  mongodb-data:   # Volume for MongoDB
    driver: local

networks:
  online-contest-net:
    name: online-contest-net