services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: contest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 05052001
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - online-contest-net
  mongodb:
    image: mongodb/mongodb-community-server:7.0-ubi9
    container_name: mongo-db
    ports:
      - "27017:27017"
    networks:
      - online-contest-net
  keycloak:
    image: keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    ports:
      - "8086:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - online-contest-net

volumes:
  postgres-data:

networks:
  online-contest-net:
    name: online-contest-net
