# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: container.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'container.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63ontainer.proto\"-\n\x15getContainerIdRequest\x12\x14\n\x0claboratoryId\x18\x01 \x01(\t\"=\n\x16getContainerIdResponse\x12\x13\n\x0b\x63ontainerId\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05\x32R\n\rRunnerService\x12\x41\n\x0egetContainerId\x12\x16.getContainerIdRequest\x1a\x17.getContainerIdResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'container_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETCONTAINERIDREQUEST']._serialized_start=19
  _globals['_GETCONTAINERIDREQUEST']._serialized_end=64
  _globals['_GETCONTAINERIDRESPONSE']._serialized_start=66
  _globals['_GETCONTAINERIDRESPONSE']._serialized_end=127
  _globals['_RUNNERSERVICE']._serialized_start=129
  _globals['_RUNNERSERVICE']._serialized_end=211
# @@protoc_insertion_point(module_scope)
