services:
  gateway:
    build: .
    ports:
      - "8080:8080"   # Spring Boot HTTP
      - "8086:8086"
#      - "9090:9090"   # gRPC
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DOTENV_PATH=.env
    networks:
      - online-contest-net

networks:
  online-contest-net:
    external: true
