services:
  gateway:
    build: .
    ports:
      - "8080:8080"   # Spring Boot HTTP
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DOTENV_PATH=.env
    networks:
      - online-contest-net

networks:
  online-contest-net:
    external: true
