global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['course-course-service-1:8082']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
#remote_write:
#  - url: '<Your Prometheus remote_write endpoint>'
#    basic_auth:
#      username: 'tad'
#      password: '<Your Grafana Cloud Access Policy Token>'