services:
  file-service:
    build: .
    ports:
      - "8087:8087"   # Spring Boot HTTP
      - "9092:9092"   # gRPC
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DOTENV_PATH=.env
    networks:
      - online-contest-net

networks:
  online-contest-net:
    external: true
