services:
  submission-service:
    build: .
    ports:
      - "8083:8083"   # Spring Boot HTTP
      - "9093:9093"   # gRPC
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DOTENV_PATH=.env
    networks:
      - online-contest-net

networks:
  online-contest-net:
    external: true
