services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - shared_volume:/shared
    container_name: fastapi_grpc_app
    ports:
      - "8084:8000"    # FastAPI
      - "50051:50051"    # gRPC
    environment:
      - MONGO_URI=mongodb://mongo-db:27017
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - online-contest-net
volumes:
  shared_volume:  # Named volume declaration
networks:
  online-contest-net:
    external: true
