version: '3.9'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 05052001
      POSTGRES_DB: contest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  course-service:
    build: .
    ports:
      - "8082:8082"   # Spring Boot HTTP
      - "9090:9090"   # gRPC
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DOTENV_PATH=.env
    depends_on:
      - postgres

volumes:
  pgdata: