name: Lint CI

on: [push, pull_request]

jobs:
  lint-python:
    runs-on: ubuntu-latest
    name: Lint Python code
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: |
          flake8 runner/ --max-line-length=88
          flake8 tester/ --max-line-length=88

  lint-java:
    runs-on: ubuntu-latest
    name: Lint Java directories
    strategy:
      matrix:
        dir: [course, file, gateway, submission, user]

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to Gradle wrapper
        working-directory: ${{ matrix.dir }}
        run: chmod +x gradlew

      - name: Run Gradle check (includes lint, tests, etc.)
        working-directory: ${{ matrix.dir }}
        run: ./gradlew check
